name: Pages

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main  # deploying branch
      # - uses: manyuanrong/setup-ossutil@v1.0
      #   with:
      #     # endpoint 可以去oss控制台上查看
      #     endpoint: "oss-cn-beijing.aliyuncs.com"
      #     # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
      #     access-key-id: ${{ secrets.ACCESS_KEY_ID }}
      #     access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      # - name: Deply To OSS
      #   run: ossutil cp public oss://lilu-blog/ -rf